# 1. Import Dependencies

In [1]:
import os
import gymnasium as gym # Build env and work with pre-existing env's.
from stable_baselines3 import PPO # SB -> high-level RL algos (e.g. PPO).
from stable_baselines3.common.vec_env import DummyVecEnv # Test multiple agents at the same time.
from stable_baselines3.common.evaluation import evaluate_policy # 
import pygame
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.callbacks import BaseCallback
from torch.utils.tensorboard import SummaryWriter


# 2. Load Environment

In [2]:
# Create Environment
environment_name = "CartPole-v1"
env = gym.make(environment_name, render_mode='human')
env = Monitor(env)
# print(environment_name)

In [3]:
episodes = 5

for episode in range(1, episodes + 1):
    state, _ = env.reset()  # Reset the environment
    done = False
    score = 0
    
    while not done:
        env.render() # Render the environment (avoid unnecessary pygame handling)
        action = env.action_space.sample()  # Generate a random action
        
        # Step through the environment
        next_state, reward, terminated, truncated, info = env.step(action)
        
        done = terminated or truncated
        score += reward

    print('Episode:{} Score:{}'.format(episode, score))

# Properly close the environment
env.close()

import pygame
pygame.quit()

Episode:1 Score:21.0
Episode:2 Score:37.0
Episode:3 Score:22.0
Episode:4 Score:11.0
Episode:5 Score:15.0


# 3. Understanding the Environment

In [4]:
env.action_space

Discrete(2)

In [5]:
env.action_space.sample()


np.int64(1)

In [6]:
env.observation_space

Box([-4.8               -inf -0.41887903        -inf], [4.8               inf 0.41887903        inf], (4,), float32)

In [7]:
env.observation_space.sample()

array([ 2.8929267 , -1.1120878 ,  0.36106884,  1.2651745 ], dtype=float32)

# 4. Train an RL Model

In [8]:
log_path = os.path.join('Training', 'Logs')
log_path

'Training/Logs'

In [9]:
env = gym.make(environment_name) # recreate env, new instance of env
env = DummyVecEnv([lambda: env]) # Wrap single env into vectorized end to create parallel envs for multi-processing
log_dir = "Training/Logs"
os.makedirs(log_dir, exist_ok=True)
model = PPO('MlpPolicy', env, verbose = 1, tensorboard_log=log_dir) # Simple NN used for policy

class TensorboardCallback(BaseCallback):
    def __init__(self, verbose=0):
        super(TensorboardCallback, self).__init__(verbose)
        self.writer = SummaryWriter(log_dir)

    def _on_step(self) -> bool:
        # Log scalar metrics
        self.logger.record('reward', self.locals['rewards'])
        # Log custom scalar to TensorBoard
        if 'reward' in self.locals:
            reward = self.locals['rewards'][0]
            self.writer.add_scalar('Reward', reward, self.num_timesteps)
        return True

    def _on_training_end(self) -> None:
        self.writer.close()

Using cpu device


In [10]:
model.learn(total_timesteps=20000, callback=TensorboardCallback())

Logging to Training/Logs/PPO_9
-----------------------------
| reward             | [1.] |
| time/              |      |
|    fps             | 8899 |
|    iterations      | 1    |
|    time_elapsed    | 0    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| reward                  | [1.]        |
| time/                   |             |
|    fps                  | 5786        |
|    iterations           | 2           |
|    time_elapsed         | 0           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.008393459 |
|    clip_fraction        | 0.0914      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.686      |
|    explained_variance   | -0.00113    |
|    learning_rate        | 0.0003      |
|    loss                 | 5.52        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0133     |
|    value_loss

# 4. Save and Reload Model

In [11]:
PPO_Path = os.path.join('Training', 'Saved Models', 'PPO_Model_Cartpole')

In [12]:
model.save(PPO_Path)

In [13]:
del model

In [14]:
PPO_Path

'Training/Saved Models/PPO_Model_Cartpole'

In [15]:
model = PPO.load(PPO_Path, env=env)

In [16]:
model.learn(total_timesteps=1000)

Logging to Training/Logs/PPO_10
-----------------------------
| time/              |      |
|    fps             | 9144 |
|    iterations      | 1    |
|    time_elapsed    | 0    |
|    total_timesteps | 2048 |
-----------------------------


# 5. Evaluation

In [17]:
from stable_baselines3.common.evaluation import evaluate_policy

mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=10, render=True)
print(f"Mean reward: {mean_reward}, Std reward: {std_reward}")

/Users/abhishekdeshpande/Library/Python/3.12/lib/python/site-packages/stable_baselines3/common/evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(
/Users/abhishekdeshpande/Library/Python/3.12/lib/python/site-packages/stable_baselines3/common/vec_env/base_vec_env.py:244: UserWarning: You tried to call render() but no `render_mode` was passed to the env constructor.
  warnings.warn("You tried to call render() but no `render_mode` was passed to the env constructor.")


Mean reward: 500.0, Std reward: 0.0


In [18]:
env.close()

# 6. Test Model

In [19]:
import numpy as np

episodes = 5

for episode in range(1, episodes + 1):
    obs = env.reset()
    done = False
    score = 0
    
    while not done:
        env.render()
        
        # Predict the action based on the current observation
        action, _states = model.predict(obs, deterministic=True)
        
        # Step through the environment
        obs, reward, done, info = env.step(action)
        
        # Ensure reward is handled as a scalar
        score += reward
        # item() if isinstance(reward, np.ndarray) else reward

    print('Episode:{} Score:{}'.format(episode, score))

env.close()

import pygame
pygame.quit()

Episode:1 Score:[500.]
Episode:2 Score:[500.]
Episode:3 Score:[500.]
Episode:4 Score:[500.]
Episode:5 Score:[500.]


In [20]:
obs = env.reset()

In [21]:
obs

array([[ 0.00483098, -0.0081717 ,  0.03065488,  0.01853669]],
      dtype=float32)

In [22]:
action, _ = model.predict(obs)

In [23]:
env.action_space.sample()

np.int64(0)

In [24]:
env.step(action)

(array([[ 0.00466755, -0.20371956,  0.03102561,  0.3207318 ]],
       dtype=float32),
 array([1.], dtype=float32),
 array([False]),
 [{'TimeLimit.truncated': False}])

# 7. Viewing Logs in Tensorboard

In [25]:
training_log_path = os.path.join(log_path, 'PPO_2')

In [ ]:
training_log_path

'Training/Logs/PPO_2'

: 